### ISSUE TITLE
[FEATURE] - Add golangci-lint GitHub Action

### ISSUE THREAD

**Issue by alex1989hu** [go-co-op/gocron#97]
### Is your feature request related to a problem? Please describe

Using popular lint tool `golangci-lint` would help to keep the code cleaner and fix the already existing issues.

### Describe the solution you'd like
- Add `.github/workflows/golangci-lint.yml`
- Remove `lint`, `fmt`, `check-fmt` and `vet`  job from `.github/workflows/go_test.yml`
- Remove `fmt`, `check-fmt` and `vet` from `Makefile`
   - Optionally keep `lint` but to call `golangci-lint`
- Create a minimal ~ permissive `.golangci.yml` as starting point
    - Listing currently enabled linters https://golangci-lint.run/usage/linters/#enabled-by-default-linters
- Fix errors reported by the default configuration 
- Enable more linters and fix issues reported by the newly activated linters

Example `YAML` based on the official repo and on your current workflow https://github.com/golangci/golangci-lint-action#how-to-use

```yaml
name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  golangci:
    strategy:
      matrix:
        go-version:
          - 1.14
          - 1.15
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33
```

### Describe alternatives you've considered

The code already provides an alternative: `golang.org/x/lint/golint`

### Additional context

N/A
